;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_jello

.segment	"RODATA"

L0003:
	.byte	$4a,$65,$6C,$6C,$6F,$2C,$20,$57,$6F,$72,$6C,$64,$21,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_jello: near

.segment	"CODE"

	lda     #<(L0003)
	ldx     #>(L0003)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L0005
L0005:	jmp     L0005
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

