#include <stdio.h>
#include <stdbool.h>

#include "../include/note.h"

int main(void)
{
  printf("Hello, World!\n");

  // 440 reads per second
  // while(true){
  //   asm("NOP");
  //   asm("NOP");
  //   asm("NOP");
  //   asm("NOP");

  //   asm("NOP");
  //   asm("NOP");
  //   asm("NOP");
  //   asm("NOP");
  //   asm("NOP");
    // asm("BIT $C030");
  //   asm("JSR $FCA8");
  // }

// TODO:
// Custom sleep loop
// Figure out the resolution of NOP instructions for making different notes? 25 seems like a good number?
// What notes are we supporting? 61-Key: C2 to C7.

  // asm("lda $64");
  // asm("jsr $fca8");
  note(0);
  while(true){
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("BIT $C030");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");
    asm("NOP");

  }

  while(true){};
  // }
  // This matters when compiling to a disk image
  //
  // If you don't add an infinite loop the emulator will quickly execute
  // and exit your program before you're able to see the output.
  // while(true);
  return 0;
}