;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_note
	.export		_rest
	.export		_end_note

.segment	"RODATA"

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"
; receive integer argument note 0-61
; wall of nop
; Duration arg stored at 0x02
; Low bits at 0x02
; High bits at 0x03
_note:
  ; Tuning is off and I'm not entirely sure why.
  ; Too many nops
  .REPEAT 4096 ; 3902 - 43 (86 cycle padding to account for work checking duration values)
  nop
  .ENDREP
_end_note:
  bit $C030

; This whole thing takes *roughly* 86 cycles

Note0_7: ; 18 cycles (not accounting for padding)
  ldx #00 ;2
  cpx $02 ;3
  bne SkipTiming0_7 ;2 if no branch, 3 if taken
  ; ONLY IF 0
  .REPEAT 4 ; 4 x 2 = 8 timing cycles
  nop
  .ENDREP
  jmp Note8_15 ;3
SkipTiming0_7:
  .REPEAT 34 ; Pad 68 cycles to account for outer loop lengths
  nop
  .ENDREP
  dec $02  ;5
  jmp ($00) ;5

Note8_15: ; 23 cycles (not accounting for padding)
  dec $02  ;5
  ldx #00 ;2
  cpx $03 ;3
  bne SkipTiming8_15 ;2 if no branch, 3 if taken
  .REPEAT 4 ; 4 x 2 = 8 timing cycles
  nop
  .ENDREP
  jmp Note16_23 ;3 if taken
SkipTiming8_15:
  .REPEAT 22 ; Pad 44 cycles to account for outer loop lengths
  nop
  .ENDREP
  dec $03 ;5
  jmp ($00) ;5

Note16_23: ;23 cycles (not accounting for padding)
  dec $03  ;5
  ldx #00 ;2
  cpx $04 ;3
  bne SkipTiming16_23 ;2 if no branch, 3 if taken
  .REPEAT 4
  nop
  .ENDREP
  jmp Note24_31 ; 3
SkipTiming16_23:
  .REPEAT 11 ; Pad 22 cycles to account for outer loop length
  nop
  .ENDREP
  dec $04 ;5
  jmp ($00) ;5

Note24_31:  ;13 if 0, otherwise 22  (not accounting for padding)
  dec $04  ;5
  ldx #00 ;2
  cpx $05 ;3
  beq NoteExit ;2 if no branch, 3 if taken
  dec $05 ;5
  jmp ($00) ;5
NoteExit:
  rts ;6

; Duration arg stored at 0x06
; Low bits at 0x06
; High bits at 0x07

; 2000 cycles total
_rest:
  .REPEAT 981
  nop
  .ENDREP
RestLowBits: ; 16 cycles always
  ldx #00 ;2
  cpx $06 ;3
  bne SkipTimingRestLow ;2 if no branch, 3 if taken
  .REPEAT 3
  nop
  .ENDREP
  jmp RestHighBits ;3 + (however many RestHighBits cycles)
SkipTimingRestLow:
  .REPEAT 11 ; pad to account for Rest HighBits
  nop
  .ENDREP
  dec $06 ;5
  jmp _rest ;3

RestHighBits: ; 22 cycles when not zero (who cares about 0 (not me!))
  dec $06 ;5
  ldx #00 ;2
  cpx $07 ;3
  beq RestExit ;2 if no branch, 3 if taken
  dec $07 ;5
  jmp _rest ;5
RestExit:
  rts