;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_note
	.export		_rest

.segment	"RODATA"

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"
; receive integer argument note 0-61
; wall of nop
_note:
  .REPEAT 3902
  nop
  .ENDREP
  bit $C030
TwoHundredInner:
  dec $02
  beq TwoHundredOuter
  jmp ($00)
TwoHundredOuter:
  lda $00 ; Check if TwoHundredOuter register value is 0
  cmp $03
  beq exit
  ldx #25 ; Set TwoHundredInner register value to 25
  stx $02
  dec $03
  jmp ($00)
exit:
  rts

_rest:
  .REPEAT 1000
  nop
  .ENDREP
  rts
